### PR TITLE
bugfix/return-accountNotFound

### PR DESCRIPTION
**Pull request by officialfrancismendoza**
**Issue** (#277): Account does not return if not found
**Fix**: Made changes to RPCHelpers.cpp to add an additional conditional under getAccount (L195) to account for account not found. Cross-referenced error codes in RPC.h and ErrorCodes.h, the latter being found in the build folder.

### CODE REVIEW

**Comment by cjcobb23** [comment]
Please give the PR a descriptive title and link to the issue in the description

**Review by cjcobb23 — CHANGES_REQUESTED** [review]
Don't think this is building correctly. Also, please reword the commit message to describe the issue and your fix

**Comment by cjcobb23** [comment]
@officialfrancismendoza this PR is not compiling

**Comment by officialfrancismendoza** [comment]
Closed until patch is implemented

**Pull request closed without merging**
