### PR TITLE
Fix code inside assert

### PR DESCRIPTION
**Pull request by kuznetsss**

### CODE REVIEW

**Review by arihantkothari — APPROVED** [review]
Thanks for the fix.

**Comment by arihantkothari** [comment]
I think you will also get this error (or warning i must say) after the changes, that's what I am getting locally...
```
/Users/ak/Dev/ak-forks/new/clio/src/data/BackendCounters.cpp:164:42: error: comparison of integers of different signs: 'ValueType' (aka 'long long') and 'const std::uint64_t' (aka 'const unsigned long long') [clang-diagnostic-sign-compare]
    assert(pendingCounter_.get().value() >= count);
```

**Review by godexsoft — APPROVED** [review]
Wow. Looks like it's really time to implement custom asserts that will work outside of debug builds 💯

**Comment by arihantkothari** [comment]
Just for the sake of learning, I am just curious why did the compiler not pick this up when compiling on Release instead of Debug ? 
1. I get that ` assert(...); becomes void; in release ` but should asserts not be there in Release as well ?
2. Even if we have something like this, should we not make a github action for building in debug mode as well ?

**Comment by arihantkothari** [comment]
Answering my own question,
1. I guess asserts are for debugging hence  it's only in Debug mode. But I guess there should be something to raise exceptions in Release mode instead of simply killing it ?

**Comment by kuznetsss** [comment]
> 1. I guess asserts are for debugging hence it's only in Debug mode. But I guess there should be something to raise exceptions in Release mode instead of simply killing it ?

We have a task #893 about that.

**Comment by arihantkothari** [comment]
> > 1. I guess asserts are for debugging hence it's only in Debug mode. But I guess there should be something to raise exceptions in Release mode instead of simply killing it ?
> 
> We have a task #893 about that.

Got it, thanks!

**Pull request merged**
