### PR TITLE
Added copyright info to each file

### PR DESCRIPTION
**Pull request by j0ker70**
[Issue] #411
[Problem] Copyright info was missing from each file of this project
[Solution] Added copyright info to each file(*.h and *.cpp)

### CODE REVIEW

**Review by godexsoft — APPROVED** [review]
Looks good!

**Comment by godexsoft** [comment]
Hi @j0ker70, a few things need to be fixed for me to merge this:

1) You gotta run clang-format against the codebase. Easiest way is to [setup githook](https://github.com/XRPLF/clio/blob/develop/CONTRIBUTING.md#install-git-hooks) or directly call 
```
bash .githooks/pre-commit
```
from the root of `clio` repo - this should automatically run clang-format on all sources.

2) You need to make sure you are signing each commit - carefully [read this](https://github.com/XRPLF/clio/blob/develop/CONTRIBUTING.md#git-commands) and see the link for GPG tutorial as well

Thanks!

**Comment by j0ker70** [comment]
My "feature" branch is showing merge conflicts whenever I am trying to change my commit. How can I edit my PR?

**Comment by godexsoft** [comment]
> My "feature" branch is showing merge conflicts whenever I am trying to change my commit. How can I edit my PR?

Looks like you signed the merge commit but did not sign the original commit still.
What i often end up doing is this:
```
$ git checkout develop
$ git pull origin develop
$ git checkout myBranch
$ git rebase -i develop
```

Then in rebase i squash everything to one commit and make sure i sign that commit.You can sign an old commit like this
```
$ git commit --amend -S
``` 

When everything is squashed as one commit on top of develop then i just 
```
$ git push --force
```

**Comment by j0ker70** [comment]
I have deleted my feature branch somehow, Now how to get back my patch from github?

**Comment by godexsoft** [comment]
> I have deleted my feature branch somehow, Now how to get back my patch from github?

You should be able to use the github cli: `gh pr checkout 434`
or you can clone [your own repo](https://github.com/j0ker70/clio) once again and  `git checkout -b feature origin/feature`.

**Comment by godexsoft** [comment]
@j0ker70 do you need more time to complete this or should I take it over?

**Comment by j0ker70** [comment]
You can take over

**Comment by godexsoft** [comment]
Closing in favour of #444 as i could not restore the branch from this pr.

**Pull request closed without merging**
