### PR TITLE
Use json value_to<string> to do the string convert

### LINKED ISSUE #953: Fix json string value conversion
There are 187 places in the code where string is getting from json as

```cpp
std::string s = json_value.as_string().c_str();
```

It potentially could cause data loss if string in json contains `'\0'`.
A better way to do it is:
```cpp
std::string s = boost::json::value_to<std::string>(json_value);
```

### PR DESCRIPTION
**Pull request by cindyyan317**
Fix #953 

Replace c_str() with value to, except the places where require a C string, like EXPECT_STREQ

### CODE REVIEW

**Comment by kuznetsss** [comment]
`EXPECT_STREQ()` was used because of `c_str()`. For example https://github.com/XRPLF/clio/blob/cce695c570057c497198f61d790e7a5c795a02d9/unittests/rpc/handlers/NFTBuyOffersTests.cpp#L487-L489

Could be replaced by 
```cpp
 EXPECT_EQ( 
     boost::json::value_to<std::string>(output->at("marker")), 
     "E6DBAFC99223B42257915A63DFC6B0C032D4070F9A574B255AD97466726FC353" 
 ); 
```

**Comment by cindyyan317** [comment]
> EXPECT_STREQ

I hesitated to change this one , because the case itself will ensure there is no '\0'. I don't bother to make it more unified. Will add this

**Review by kuznetsss — DISMISSED** [review]
👍

**Review by godexsoft — DISMISSED** [review]
👍

**Review by kuznetsss — APPROVED** [review]

**Pull request merged**
