### PR TITLE
Add README section for database administration

### PR DESCRIPTION
**Pull request by Mwni**
Adds a remark about Scyllas default memory reservation behavior and how to change it.

### CODE REVIEW

**Review by natenichols — COMMENTED** [review]
Thanks for noting this. This is important to add for people setting Clio up locally.

Personally, I would prefer linking to [this](https://docs.scylladb.com/getting-started/scylla-in-a-shared-environment/) doc.

We can also mention both relevant cli arguments: 
Number of cores:
```
--smp 2
```
and memory:
```
--memory 2GB
```

I'll leave the phrasing up to you.

**Comment by Mwni** [comment]
The link has been replaced. However I do feel that now the statement no longer exactly represents what the link is pointing to.

**Review by natenichols — APPROVED** [review]

**Comment by natenichols** [comment]
Looks good to me. You'll have to squash and sign your commits before we can merge.

**Comment by Mwni** [comment]
Done.

**Comment by cjcobb23** [comment]
Merged in `92a072d7a8e7d2757599d5384a63a0b234d7cbae`

**Pull request closed without merging**
